# Generated by Django 4.0.3 on 2022-04-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='admin_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
